Job description file for vep annotation
Alexey Larionov, 25Aug2016

TEMPLATE v1

=========== Data location and analysis settings =============

Data server: admin@mgqnap.medschl.cam.ac.uk
Project location: /share/alexey

project: project1
dataset: variantset1_filter1

======================= HPC settings ========================

working_folder: /scratch/medgen/users/alexey

Account to use on HPC: TISCHKOWITZ-SL2
Max time to request (hrs.min.sec): 09.00.00

==================== Pipeline summary ======================

#Annotating filtered vcfs with vep

===================== Standard settings =====================

scripts_folder: /scratch/medgen/scripts/wes_pipeline_08.16/p07_wes_annotate_vep
start_script: a00_start_pipeline.sh

Tools and resources
-------------------

tools_folder: /scratch/medgen/tools

ensembl_version: v82
ensembl_api_folder: ensembl
vep_script: ensembl-tools/scripts/variant_effect_predictor/variant_effect_predictor.pl
vep_cache: grch37_vep_cache

Additional settings
-------------------

vcf_vep_fields: SYMBOL,Allele,ALLELE_NUM,Consequence,IMPACT,CLIN_SIG,SIFT,PolyPhen,Existing_variation,GMAF,cDNA_position,CDS_position,Codons,Protein_position,Amino_acids,DISTANCE,STRAND,SYMBOL_SOURCE
