Job description file for combining gvcfs
Alexey Larionov, 30Aug2016

TEMPLATE v1

=========== Data location and analysis settings =============

Data server: admin@mgqnap.medschl.cam.ac.uk
Project location: /share/eleanor/gastric_Aug16

project: gastric
libraries: IGP_L1
set_id: IGP_L1

======================= HPC settings ========================

working_folder: /scratch/medgen/users/eleanor/Pipeline_working_directory/gastric_Aug16

Account to use on HPC: TISCHKOWITZ-SL2
Max time to request (hrs.min.sec): 6.00.00

==================== Pipeline summary =======================

#Pipeline combines gvcfs to prepare them for joined variant calling. 
#This step is recommended by GATK for convinience in processing of 
#large numbers of samples (e.g. combine gvcfs for each 100 samples) 

===================== Standard settings =====================

scripts_folder: /scratch/medgen/scripts/wes_pipeline_08.16/p04_wes_combine_gvcfs
start_script: a00_start_pipeline.sh

Tools
-----

tools_folder: /scratch/medgen/tools
java: java/jre1.8.0_40/bin/java
gatk: gatk/gatk-3.6-0/GenomeAnalysisTK.jar

Resources
---------

resources_folder: /scratch/medgen/resources

decompressed_bundle_folder: gatk_bundle/b37/decompressed
ref_genome: human_g1k_v37.fasta

targets_folder: illumina_nextera
targets_intervals: nexterarapidcapture_exome_targetedregions_v1.2.b37.intervals

Working sub-folders
-------------------

combined_gvcfs_folder: combined_gvcfs
